name: schedule_4k_main

# Run this workflow every time a new commit pushed to your repository
on:
  schedule:
#     - cron: 0 1,5,9,13,17,21 * * *
    - cron: 7 5,11,17,23 * * *



jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  logon1:
    # Name the Job
    name: logon
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: install packages
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
          GITHUB_AUTH: ${{ secrets.BKAUTH}}
        run: |
          cd ../../
          pwd
          git clone https://$GITHUB_AUTH@github.com/brokenjade3000/colab_auto.git
          cd colab_auto
          chmod 775 ./script/install.sh
          ./script/install.sh

      # Runs the Super-Linter action
      - name: Run on brochjad4k_main
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
        run: |
          pwd
          cd /home/runner/work/colab_auto/colab_auto
          firefox --version
          python --version
          python RunColab.py encrypted_brokjad_cookies.txt lab4k.txt


